apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleetlock
rules:
  - verbs:
      - use
    apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - cadvisor
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
